from pathlib import Path
p=Path('backend/app/graph/project_repository.py')
s=p.read_text(encoding='utf-8')
def r(o,n):
 global s
 if o not in s: raise SystemExit('guard failed: '+o[:70])
 s=s.replace(o,n,1)
r('''    def create_project(self, name: str, internal_code: str | None) -> Project:\n        project = Project(\n            id=str(uuid4()),\n            name=name,\n            internal_code=internal_code,\n        )\n        self._driver.execute_query(\n            """\n            CREATE (project:Project {\n                id: $id,\n                name: $name,\n                internalCode: $internal_code,\n                createdAt: datetime()\n            })\n            """,\n            id=project.id,\n            name=project.name,\n            internal_code=project.internal_code,\n            **self._query_config,\n        )\n        return project\n''','''    def create_project(self, name: str, internal_code: str | None) -> Project:\n        project_id = str(uuid4())\n        result = self._driver.execute_query(\n            """\n            CREATE (project:Project {\n                id: $id, name: $name, internalCode: $internal_code,\n                createdAt: datetime(), updatedAt: datetime()\n            })\n            RETURN toString(project.createdAt) AS createdAt,\n                   toString(project.updatedAt) AS updatedAt\n            """,\n            id=project_id, name=name, internal_code=internal_code, **self._query_config,\n        )\n        records = getattr(result, "records", None)\n        if records is None and isinstance(result, tuple) and result:\n            records = result[0]\n        record = records[0] if records else None\n        return Project(\n            id=project_id, name=name, internal_code=internal_code,\n            created_at=(record.get("createdAt") if record is not None else None),\n            updated_at=(record.get("updatedAt") if record is not None else None),\n        )\n''')
r('''            MATCH (project:Project)\n            RETURN project.id AS id, project.name AS name, project.internalCode AS internalCode\n            ORDER BY project.createdAt DESC, project.name ASC\n''','''            MATCH (project:Project)\n            RETURN project.id AS id, project.name AS name, project.internalCode AS internalCode,\n                   toString(project.createdAt) AS createdAt, toString(project.updatedAt) AS updatedAt\n            ORDER BY CASE WHEN project.createdAt IS NULL THEN 1 ELSE 0 END ASC,\n                     project.createdAt DESC, project.name ASC, project.id ASC\n''')
r('''                internal_code=record["internalCode"],\n            )\n            for record in result.records\n''','''                internal_code=record["internalCode"],\n                created_at=record.get("createdAt"), updated_at=record.get("updatedAt"),\n            )\n            for record in result.records\n''')
r('''        project = Project(\n            id=project_node["id"],\n            name=project_node["name"],\n            internal_code=project_node.get("internalCode"),\n        )\n''','''        project = Project(\n            id=project_node["id"], name=project_node["name"], internal_code=project_node.get("internalCode"),\n            created_at=(str(project_node.get("createdAt")) if project_node.get("createdAt") is not None else None),\n            updated_at=(str(project_node.get("updatedAt")) if project_node.get("updatedAt") is not None else None),\n        )\n''')
r('''            MATCH (project:Project {id: $project_id})\n            MERGE (document:Document {projectId: $project_id, kind: $kind})\n''','''            MATCH (project:Project {id: $project_id})\n            SET project.updatedAt = datetime()\n            MERGE (document:Document {projectId: $project_id, kind: $kind})\n''')
r('''            MATCH (project:Project {id: $project_id})\n            OPTIONAL MATCH (project)-[:HAS_REVIEW_ROUND]->(existing:ReviewRound)\n''','''            MATCH (project:Project {id: $project_id})\n            SET project.updatedAt = datetime()\n            OPTIONAL MATCH (project)-[:HAS_REVIEW_ROUND]->(existing:ReviewRound)\n''')
r('''            MATCH (project:Project {id: $project_id})-[:HAS_REVIEW_ROUND]->(round:ReviewRound {id: $round_id})\n            SET round.status = 'approved',\n''','''            MATCH (project:Project {id: $project_id})-[:HAS_REVIEW_ROUND]->(round:ReviewRound {id: $round_id})\n            SET project.updatedAt = datetime(),\n                round.status = 'approved',\n''')
p.write_text(s,encoding='utf-8')
